[pytest]
testpaths = tests
pythonpath = .
filterwarnings =
    ignore:Could not find the number of physical cores:UserWarning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
